version: '3.8'


volumes:
  postgres_data:
  static_volume:


services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
      
  web:
    image: alexey156/foodgram_project:latest
    restart: always
    command: sh -c "python manage.py makemigrations --noinput && python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/code/static/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.0
    volumes:
      - static_volume:/code/static/
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - web
